### ISSUE TITLE
[CTW/12vs12] Santa Clauses

### ISSUE THREAD

**Issue by Akinakumushi** [OvercastCommunity/CommunityMaps#93]
### Checklist
Check what applies to you. *Add an X between the brackets or click the checkboxes when you have submitted the issue.*
- [X] I have [pruned](https://pgm.dev/docs/guides/packaging/pruning-chunks) the map
- [X] I have agreed with assigning the CC BY-SA license to this map, as mentioned in the README
- [X] I have created an XML file
- [X] I have created an map image
- [X] I have uploaded the map zip file to a file sharing service
- [X] The map has been tested locally to make sure it works

# Map Name
Santa Clauses

## Gamemode & Map Description  
This is a CTW map, produced for the holiday season 🎅
I'm still considering Team Sizes in either 12vs12 or 16vs16.

## Team Sizes
12vs12

## Screenshots
https://imgur.com/gallery/NF8cOrl

# XML
https://gist.github.com/Akinakumushi/834953cccea873953b21908b31706edb

# Map Image
![map](https://user-images.githubusercontent.com/75409727/100984423-10e4f280-358e-11eb-849e-99def369f306.png)

# Download Link
https://www.dropbox.com/s/x4dm8081g4coo3r/Santa%20Clauses%27%20Ready%20v1.0.0.zip?dl=0

**Comment by CrazyisCreeps** [comment]
Sweet, awesome map for the holidays! I'll take a look at the map, and unless there's any major issues that need to be tackled, I'll load this up until the rest of the Christmas maps go

**Comment by CrazyisCreeps** [comment]
Alright so a couple issues I found. First off, here's the xml, fixed to the point that it loads. 

Secondly, your regions aren't quite set up right and you can't bridge anywhere. It's unclear where you intended to allow bridging to happen, so it's very hard for me to try and fix this myself. Either place block 36 at y=0 for all the areas you want to allow bridging, or specify lanes in the xml to allow bridging to happen. Right now I see there's a negative of field, am I to assume you're supposed to be able to bridge everywhere inside of the field region? It's really not clear. If you're not sure how to fix it, let me know what the intended regions are and I can get it done up.

To quickly bump off of that issue, you'd also need to place block 36 under all the areas of the map with lanes built, as there's no block there right now and the void filter is preventing any and all interactions with the map.

Another issue, the map needs to be pruned a little more aggressively. There's water & lava on the edges of the map, as well as a couple of leaves.

Finally, you're able to enter your own team's wool room.

**Comment by Akinakumushi** [comment]
@CrazyisCreeps Thank you for the feedback, Crazy_ 🙇‍♂️💦💦
I'll be fixing the issues and updating this map in the next few days.

**Comment by Akinakumushi** [comment]
# Update the map to v1.0.1 :rocket:

**Major Changes**

　・Fixed a problem where regions aren't quite set up right. (L 120~239)
　　The deny-void filter has been removed by setting each void area.

　・Eliminated cobblestone, lava, leaves & water that had not been fully deleted.
　　Also, file size was reduced by pruning unnecessary chunks.

　・Added locations for the wool rooms under the <wools> module. (L 100, 105)

**Other Changes**

　・Removed ['(apostrophe)] from the map name based on the [naming conventions](https://pgm.dev/docs/guides/xml-pointers/conventions#naming-conventions).
　　Changed to Santa Clauses (because I want many many requests 🙃)

　・Added max-overfill under the <teams> module. (L 17, 18)

　・Removed glass from the spawn kit and added yellow terracotta instead,
　　Tweaked the quantity of building blocks in the spawn kit.

Regarding the problem of being able to enter your own team's wool room,
I was unable to identify the cause, so I'm not sure if it will work properly.
(I tried reversing the order of the element attributes block and enter protection)

# XML
https://gist.github.com/Akinakumushi/93f8a7cd36626a8a999fdf72400e6497/revisions

# Download Link
**Click [here ](https://www.dropbox.com/s/e2vn3ow31a2kt7z/Santa%20Clauses%20v1.0.1.zip?dl=0)to download the latest version (v1.0.1) Thank you!**

**Comment by CrazyisCreeps** [comment]
Are these regions the areas that are void, or are these areas where the map is? https://gist.github.com/Akinakumushi/93f8a7cd36626a8a999fdf72400e6497/revisions#diff-e72614d604c5492cede6634d55d60e64face866435ab94c99f03e04f6bbd65a5R189

**Comment by Akinakumushi** [comment]
Lines 189~230 describe the void areas where I don't want to place blocks.
[This image](https://imgur.com/mqeH54O) that shows the protected area of the entire map. Please check it!

**Comment by CrazyisCreeps** [comment]
Okay, the reason I ask is because I'm still unable to place blocks anywhere on the map. But gimme a day or two, I'll get it fixed up using your picture as a guide!

**Comment by CrazyisCreeps** [comment]
Does this just ensure that there's always wool to break? https://gist.github.com/Akinakumushi/93f8a7cd36626a8a999fdf72400e6497/5f83696031c19a85fd5072c37780dc30c9ee7bfa#file-map-xml-L240

**Comment by CrazyisCreeps** [comment]
Alright so I've been busy, I hope you don't mind but since I really wanted to try and get this map loaded up with the Christmas maps in the pool I fixed a lot of the map issues myself. Here's your new map download https://www.dropbox.com/s/gmr0exft4axv1l5/Santa%20Clauses.zip?dl=0

I fixed some issues with the world itself as well as the xml. Let's start with the world
- Removed unpruned chunks, removed full chunks left behind
- Spaced out webs near wool room lanes to prevent people making bridges off them
- Added a block behind the floating ladder at spawn, as breaking it could cause issues and players wouldn't be able to re-enter spawn. Now with the full block behind it, it doesn't all break as one chain.

As for the xml, you'll notice it looks a little different. I redid it completely, I found it was really hard to figure out what was what and here's the changes otherwise
- Fixed void filters. I added block 36 under every area that allows placing or breaking blocks. Now it all works as intended.
- Removed chest protection for the defense supply chest. It'll only get in the way if players want to break down that wall area.
- Reworked the other chest protection to prevent wool chests from being broken
- Added unbreaking to all the tool/armour

Now the line I commented about a few hours ago....that module doesn't work. Depending on what the point of it was, I can try to fix it up, use a different module, or scrap it. Let me know. I'm going to load the map up to be able to get some gameplay tests, I'll let you know how those go. Feel free to ask a mod to set the map for you if you'd like to play it yourself. 😄

**Comment by Akinakumushi** [comment]
Thank you for all that you've done for me, Crazy_ 😭

**Comment by CrazyisCreeps** [comment]
Oh it's all good, don't worry about that.

After testing it out a few times, I think it would improve the gameplay if the void gap was increased between the two sides. I find rushing is super easy on this map and it's hard to find a match that lasts more than 5 or 6 minutes. A little spacing would go a long way to improve the map 👌

**Comment by Akinakumushi** [comment]
# Update the map to v1.0.2 :rocket:

**Major Changes**

　・Increased the [void gap](https://imgur.com/gallery/t8EFu4Z) in the center of the map.
　　(Specifically, it's about twice as big as used to be)

　・Changed the coordinates in the XML accordingly.

　・Placed a bedrock barrier in the ground to increase the difficulty
　　of entering the wool room.

**Other Changes**

　・Added resistance effect when spawning to prevent fall damage.

　・Replace all water in the map with light blue stained glass.

Apologize for the last minute update.
I hope you have a wonderful Christmas! 🎄

# XML
https://gist.github.com/Akinakumushi/93f8a7cd36626a8a999fdf72400e6497/revisions

# Download Link
**Click [here](https://www.dropbox.com/s/pn0ac125e6hmcws/Santa%20Clauses%20v1.0.2.zip?dl=0) to download the latest version (v1.0.2) Thank you!**

**Comment by technodono** [comment]
this map has been in here forever and should probably be closed untill the author becomes active again

**Comment by CoWinkKeyDinkInc** [comment]
After attempting to contact the map author 3 days ago (December 1 2021) with no response, it seems to me that this map has finished any further development. Version 1.0.2 finally added in 048599f.
